name: Version Bump
on:
    create:
permissions:
  contents: write

jobs:
    bump-version:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
            
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.x'
            - run: pip install -r requirements.txt
            
            - name: Run version bump script
              run: python version.py
            
            - name: Commit & Push changes
              uses: actions-js/push@master
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}